version: "3.8"

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql8-test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql-data:/tmp/testing-mysql2
      - ./db-scripts:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8mb3_general_ci
      - --skip-character-set-client-handshake
